#listas
#EN PYTHON TODO ES UN OBJETO, COMO TODO ES UN OBJEO SIGNIFICA Q TODOS LOS ELEMENTOS (VARIABLES,BOOLEANOS, STRING,ETC) TIENEN MAS POWER
listas = [0,1,"ASD",3,4] #ESTA LISTA ESTA INDEXADO 
#LA LISTA PUEDE SER DE DISTINTIOS TIPOS DE DATOS 
#OTRA FORMA DE DECLARAR UNA LISTA 
variable = list(1,2,3,4,"sas")
#INDEXADO ES DECIR Q SE PUEDE ACCEDER POR INDICES 
#LA LISTA ES UN CONJUNTO DE ELEMENTOS A LA CUAL YO PUEDO ACCEDER
#LAS LISTAS SE PUEDEN MODIFICAR 
#SE PUEDEN ORDENAR, AGREGAR ELEMENTOS, BORRAR ELEMENTOS Y SE PUEDEN RECORRER 
#ES DECIR Q LA LISTAS SON DINAMICAS, SE PUEDEN MODIFICAR ES DECIR ES MUTABILIDAD 
#append es para agregar
#len para conocer el tamaño 

