# PYTHON ORIENTADO A OBJETOS:
# SE LLAMA OBJETOS PORQUE ANTES TENIAMOS LAS COSAS SUELTAS EN VARIABLES Y PARA RELACIONAR DATOS TENIAMOS QUE TRABAJAR LISTAS DE FORMA PARALELA
# PARA QUE ESOS INDICES TENGAN SIGNIFICADO, TAMBIEN PODIAMOS TRABAJR CON LISTAS DE DICCIONARIO, POR UN LADO TENIAMOS LOS DATOS POR OTRO LADO
# TENIAMOS LAS FUNCIONES QUE SE TRABAJABAN RELACIONADOS CON ESOS DATOS, ENTONCES LA PROGRAMACION ORIENTADA A OBJETOS LO QUE HACE ES INTEGRAR 
# BASICAMENTE LOS DATOS CON LAS FUNCIONES, ES DECIR UN OBJETO VA A TENER EN SI MISMO DATOS QUE SON PROPIOS DE ESE OBJETO Y FUNCIONES 
# QUE SON PROPIOS DE ESE OBJETOS. A LAS VARIABLES DE TIPO DATO LO VAMOS A LLAMAR ATRIBUTOS Y A LAS FUNCIONES QUE FORMAN PARTE DEL OBJETO LO LLAMAMOS METODO
# LOS METODOS SON UN TIPO DE FUNCION EN PARTICULAR QUE FORMAN PARTE DE UNA VARIABLE QUE ESTA VARIABLE TERMINA SIENDO UN OBJETO
#SE AGRUPAN PROPIEDADES Y COMPORTAMIENTOS EN ALGO QUE ES CLASS O CLASE Y ESA CLASE VA A TENER DENTRO PROPIEDADES QUE VAN A SER VARIABLES O DATOS
#Y COMPORTAMIENTOS QUE VAN A SER FUNCIONES O METODOS.
#CUANDO TRABAJAMOS CON CLASES O OBJETOS SE LLAMAN PROPIEDADES 
#FUNCIONES CUANDO ESAS FUNCIONES LAS DEFINIMOS EN UNA CLASE QUE LUEGO ESA CLASE VA A SER UN OBJETO Y ESE COMPORTAMIENTO O FUNCION LO VAMOS A REFERIR COMO METODO
#QUE ES UNA CLASE Y QUE ES UN OBJETO??
#CUANDO HABLAMOS DE CLASE HABLAMOS DE UNA COSA GENERAL O GENERALIZACION Y CUANDO HABLAMOS DE OBJETO HABLAMOS DE ALGO ESPECIFICO O COSA PARTICULAR DE ESA
#GENERALIDAD. PODRIAMOS TENER LA CLASE PERSONA Y EL OBJETO DE ESA PERSONA QUE SERIA CARLOS FERNANDO
#Y TRADUCIR ESTO EN LA PROGRMAAMCION ORIENTADA A OBJETO ES QUE LA CLASE DE PERSONA VA A TENER NOMBRE ES DECIR UN ATRIBUTO QUE SE LLAME NOMBRE
#VA A TENER UN ATRIBUTO QUE SEA EL DNI OTRO QUE SEA EL DOMICILIO, Y ASI CON LOS DATOS PARTICULARES QUE TODA PERSONA TIENE 
#LO CUAL VENDRIA A SER DATOS QUE TODA PERSONA TIENE POR ESA MISMA RAZON SERIA ALGO GENERICO, AHORA SI DECIMOS X PERSONA CON X DNI HACEMOS REFERENCIA
#A UNA PERSONA EN PARTICULAR Y ESA PERSONA EN PARTICULAR VA A SER UN OBJETO, Y DE MANERA GENERICA CON SOLO LAS PROPIEDADES VA A SER UNA PERSONA
#ES DECIR VA A SER UNA CLASE YA QUE LOS DATOS LOS TIENE TODAS LAS PERSONAS
#PARA LA PERSONA TAMBIEN EXISTEN COMPORTAMIENTOS, COMER CAMINAR HABLAR DORMIR. Y ESTOS COMPORTAMIENTOS LOS VAMOS A TRABAJAR A PARTIR DE FUNCIONES DENTRO
#DE LA CLASE O CLASS Y ESAS FUNCIONES QUE VAN A ESTAR DENTRO DE LA CLASE PARA NOSOTROS CUANDO SEAN OBJETOS VAN A SER METODOS
#
#SI PENSAMOS EN UNA TARJETA DE CREDITO LAS PROPIEDADES SERIAN EL NUMERO DE TARJETA, APELLIDO, NOMBRE Y EL METODO SERIAN ACTIVAR ESA TARJETA, ANULARLA
#Y LA CLASE VA A TENER UN NUMERO DE TARJETA, TITULAR, ES DECIR TODAS LAS TARJETAS TIENEN ESO PERO UNA VA A SER DIFERENTE A OTRA PORQUE NO TODAS TIENEN EL MISMO
#NOMBRE.
#SE PUEDE EVITAR LA PROGRAMACION ORIENTA A OBJETOS, PERO SIEMPRE ES MEJOR TRABAJAR CON PROGRAMACION ORIENTADA A OBJETOS YA QUE LA PROGRAMACION ESTRUCTURADA
#ES PREVIA A LA PROGRAMACION DE OBJETOS POR LO CUAL PODEMOS DECIR QUE LA PROG ORIENDATA A OBJETOS MEJORA, EVOLUCIONA LA PROGRAMACION ESTRUCTURADA
#LA ESTRUCTURA DE DATOS PRIMITIVOS SON VARIABLES, DE TIPO CADENA, NUMERICA,BOOL Y DESPUES TENEMOS LISTAS, DICCIONARIOS Y TODO ESTO NOS SIRVE PARA TENER 
#DATOS DE MANERA SIMPLE, CON LISTAS PARALELAS PERO DESPUES PODEMOS HACER ALGO MAS SOTIFISCADO A PARTIR DE ESOS DATOS PRIMITIVOS 
#
#CADA UNA DE NUESTRAS FUNCIONES VA A TRABAJAR CON PARAMETROS Y ESOS PARAMETROS SIEMPRE VAN A RECIBIR EL DICCIONARIO QUE REPRESENTE A ESE PERSONAJE
#O LA LISTA DE DICCIONARIO DE TODOS LOS PERSONAJES. COMO LOS EJERICICOS DE DATA STARK
#TODAS LAS FUNCIONES Q VOY A IR DESARROLLANDO RECIBEN SIEMPRE COMO PARAMETRO EL DICCIONARIO O LA LISTA DE DICCIONARIO 
#PENSANDO EN CUALQUIER FUNCION QUE SE NOS OCCURA
#LA FUNCION COMIENZA CON EL NOMBRE DE DATO QUE ESTAMOS TRABJANADO EJ PERSONAJE_MOSTRAR, PERSONAJE_LISTAR
#SIEMPRE COMENZAMOS CON EL DATO DEL NOMBRE QUE TRABAJAMOS Y ESE DATO ES EL DICCIONARIO
#HASTA VENIAMOS TRABAJANDO DE ESTE MODO, EN LOS EJERCICIOS
#
#CLASES:
#LA PALABRA RESERVADA class Y ES LA QUE UTILIZAMOS PARA PROGRAMAR UNA CLASE SEGUIDO DEL NOMBRE DE LA CLASE QUE DEBE REPRESENTAR DE MANERA GENERICA
#EL GRUPO O CONJUNTO DE INDIVIDUOS QUE VAMOS A TRABAJAR EJ: class Personaje_Heroes: SE ESCRIBE CONO INICIAL CON MAYUSCULA 
#class Personaje:
#pass (aca van las variables o atributos)
#
#PROPIEDADES/ATRIBUTOS:
#SON LAS VARIABLES QUE TODOS LOS OBJETOS DEL TIPO PERSONAJE DEBEN TENER SE DEFINE EN UN METODO LLAMADO INIT O EL CONSTRUCTOR
#_init_ ES LO PRIMERO QUE SE VA A EJECUTAR CUANDO SE CREA UN OBJETO DE UNA CLASE DETERMINADA, SE CONSTRUYE EN MEMORIA LA VARIABLE Y ESA VARIABLE O ESE OBJETO
#DE LA CLASE VA A TENER ASOCIADO OTRAS VARIABLES COMO id,apellido,edad Y CUANDO SE CONSTRUYE ESE OBJETO O CUANDO SE INSTANCIA UN OBJETO DE UNA CLASE DETERMINADA
#PASA A DEJAR DE SER UNA CLASE GENERICA O GENERAL Y PASA A SER UN OBJETO EN ESPECIFICO 
#
#class Personaje:
#   def _init_(self,id,nombre,apellido,edad)->None: #SIEMPRE EL PRIMER PARAMETRO VA A SE self "si mismo" Y LUEGO VAN LOS PARAMETROS Q SON LOS ATRIBUTOS DE ESA CLASE
#       self.id=id #crea un atributo id y le asigna el valor id
#       self.nombre=nombre
#       self.apellido=apellido
#       self.edad=edad #LA EDAD VA A SER ASIGNADO A LO OBJETO.EDAD 

#id,nombre;apellido Y edad SON PARAMETROS QUE SE RECIBEN EN EL MOMENTO DE LA CREACION DEL OBJETO POR LO TANTO NO SON LO MISMO QUE self.edad,self.apellido, ETC
#NO RETORNA NADA PORQUE EL CONSTRUCTOR SE VA A OCUPAR DE DAR LOS DATOS CORRESPONDIENTES A CADA UNO DE LOS ATRIBUTOS O PROPIEDADES QUE VA A TENER EL OBJETO
#CUANDO DECLARO UNA CLASE TODO LO QUE DEFINAS ADENTRO VA A SER METODOS
#SALVO EN EL CONSTRUCTOR OSEA EL init ESTE INICIA EL ESTADO, SON LOS VALORES CON LOS CUALES VA A INICIAR EL OBJETO
#EL self SE TIENE QUE PASAR SIEMPRE
#LA CLASE VA A TENER METODOS O FUNCIONES Y ATRIBUTOS
#EL CONSTRUCTOR VA A SER EL PRIMER METODO O LA PRIMERA FUNCION QUE SE VA A EJECUTAR SIN SIQUIERA LLAMAR AL METODO init AUTOMATICAMENTE SE VA A EJECUTAR
#LOS CONSTRUCTORES EN PYTHON SE TRABAJAN A PARTIR DE ESE METODO SIEMPRE EL PRIMER PARAMETRO DE ESE METODO VA A SER self Y LUEGO LOS DEMAS PARAMETROS QUE FORMAN
#PARTE COMO PROPIEDADES ATRIBUTOS DE LA CLASE Y NO RETORNA NADA.
#



# LO QUE HACE ES INTEGRAR LOS DATOS CON LAS FUNCIONES, ES DECIR UN OBJETO VA A TENEER EN SU MISMO DATOS QUE SON PROPIOS DE ESE OBEJTO
# Y FUNCIONES QUE SON PROPIOS QUE SON TMB DE ESE OBEJTO, A LA PRIMERA SE LLAMA ATRIBUTOS Y SEGUNDA ---
# SE AGRUPAN PROPIEDADES Y COMPORTAMIENTOS ---
# QUE ES UNA CLASE Y QUE ES UN OBJETO?? 
# ESTRUCTURAS DE DATOS PRIMITIVOS SON NUMEROS, CADENAS, DICCIONARIOS Y LISTAS
# SI QUIERO REPRESENTAR ALGO MAS COMPLEJO, UNA ALTERNATIVA SERIA CON VARIABLES INDIVIDUALES, OTRA ALTERNATIVA ES LISTA, OTRA ALTERNATIVA ES DICCIONARIO
# LA MEJOR OPCION ES DICCIOANRIO O DICT, UNA LISTA UTILIZANDO DICCIONARIO 
# COMO DEFINIR CLASE ? 
# COMIENZA CON LAS PALABRA class SEGUIDA DEL NOMBRE DE LA CLASE Y LOS DOS PUNTOS 
# class Personaje:
#   pass (ACA ADENTRO VAN LAS VARIABLES O ATRIBUTOS)
# PROPIEDAS/ATRIBUTOS
# SON LAS VARIABLES, SE DEFINEN EN UN METODO LLAMADO __init__ 
# class personaje
#   def __init__(self,id,nombre,apellido,edad) -> None:
#       self.id = id #crea un atributo id y le asigna el valor id
#       self.nombre = nombre
#       self.apellido = apellido
#       self.edad = edad
# CREAS UNA INSTANCIA 
# LA CREACION DE UN OBJETO A PARTIR DE UNA CLASE  SE DENOMINA INSTANCIA DE UN OBJETO, SE PUEDE ---
# ACCEDE A LOS ATRIBUTOS, SE PUEDE ACCEDER MEDIANTE NOTACION DE PUNTOS
# COMO DEFINIR METODOS --- 
